export const dummyComments = [
    {
        id: 1,
        comment: 'Akhirnya yg di tunggu2 WETON88',
        account: 'user123',
        is_spam: true,
        is_judol: true,
        is_hidden: false,
        sentiment: -1,
    },
    {
        id: 2,
        comment: 'bang kangen',
        account: 'agus raihan...',
        is_spam: false,
        is_judol: true,
        is_hidden: false,
        sentiment: 1,
    },
    {
        id: 3,
        comment: 'absen bang',
        account: 'user123',
        is_spam: true,
        is_judol: false,
        is_hidden: false,

        sentiment: 0,
    },
    {
        id: 4,
        comment:
            'Akhirnya yg di tunggu2 gacorrr WETON88 fawd dawkd nalf ffwfew...',
        account: 'agus raihan...',
        is_spam: false,
        is_judol: true,
        is_hidden: false,
        sentiment: -1,
    },
    {
        id: 5,
        comment: 'udah yappingya?',
        account: 'user123',
        is_spam: false,
        is_judol: true,
        is_hidden: false,
        sentiment: 0,
    },
    {
        id: 6,
        comment:
            'Akhirnya yg di tunggu2 gacorrr WETON88 fawd fewed fwefwf fwe...',
        account: 'agus raihan...',
        is_spam: true,
        is_judol: true,
        is_hidden: false,
        sentiment: -1,
    },
    {
        id: 7,
        comment: 'Akhirnya yg di tunggu2 WETON88',
        account: 'user123',
        is_spam: true,
        is_judol: true,
        is_hidden: false,
        sentiment: -1,
    },
    {
        id: 8,
        comment: 'Akhirnya yg di tunggu2 gacorrr WETON88 fawd .fwefwew',
        account: 'agus raihan...',
        is_spam: true,
        is_judol: true,
        is_hidden: false,
        sentiment: -1,
    },
    {
        id: 9,
        comment: 'Akhirnya yg di tunggu2 WETON88',
        account: 'user123',
        is_spam: true,
        is_judol: true,
        is_hidden: false,
        sentiment: -1,
    },
    {
        id: 10,
        comment:
            'Akhirnya yg di tunggu2 gacorrr WETON88 fawd afawfe fwefw fw...',
        account: 'agus raihan...',
        is_spam: true,
        is_judol: true,
        is_hidden: false,
        sentiment: -1,
    },
    {
        id: 11,
        comment: 'WETON88 gacor parah guys buruan join!',
        account: 'bot_akun01',
        is_spam: true,
        is_judol: true,
        is_hidden: false,
        sentiment: -1,
    },
    {
        id: 12,
        comment: 'Nice video, bro! Suka banget sama pembahasannya 👍',
        account: 'nonton_aktif',
        is_spam: false,
        is_judol: true,
        is_hidden: false,
        sentiment: 1,
    },
    {
        id: 13,
        comment: 'Gabut banget liat video ini wkwk',
        account: 'gabuters',
        is_spam: false,
        is_judol: false,
        is_hidden: false,
        sentiment: 0,
    },
    {
        id: 14,
        comment: 'Main slot makin cuan di WETON88',
        account: 'iklan_cuan88',
        is_spam: true,
        is_judol: true,
        is_hidden: false,
        sentiment: -1,
    },
    {
        id: 15,
        comment: 'Video ini membantu banget, makasih ya 🙏',
        account: 'realuser456',
        is_spam: true,
        is_judol: false,
        is_hidden: false,
        sentiment: 1,
    },
    {
        id: 16,
        comment: 'Gila sih menang 3jt di BO ini!',
        account: 'cuanmania77',
        is_spam: true,
        is_judol: true,
        is_hidden: false,
        sentiment: -1,
    },
    {
        id: 17,
        comment: 'Penjelasan di menit 5 itu bener-bener mindblowing 🔥',
        account: 'aktifkomentator',
        is_spam: true,
        is_judol: false,
        is_hidden: false,
        sentiment: 1,
    },
    {
        id: 18,
        comment: 'Wkwkwk kocak banget ekspresinya 😂',
        account: 'hiburanmalam',
        is_spam: false,
        is_judol: false,
        is_hidden: false,
        sentiment: 1,
    },
    {
        id: 19,
        comment: 'Numpang iklan, yang mau join BO gacor cek bio ya!',
        account: 'spam_iklan99',
        is_spam: true,
        is_judol: true,
        is_hidden: false,
        sentiment: -1,
    },
    {
        id: 20,
        comment: 'Agak kurang jelas sih bagian akhirnya',
        account: 'kritikus_santai',
        is_spam: false,
        is_judol: false,
        is_hidden: false,
        sentiment: 0,
    },
    {
        id: 21,
        comment: 'Biasa aja sih, kayak konten lain',
        account: 'penonton_netral',
        is_spam: false,
        is_judol: false,
        is_hidden: false,
        sentiment: 0,
    },
    {
        id: 22,
        comment: 'Nonton ini bikin gua pengen main slot lagi 😅',
        account: 'ngacengslot88',
        is_spam: true,
        is_judol: true,
        is_hidden: false,
        sentiment: -1,
    },
    {
        id: 23,
        comment: 'Thank you for the honest review! Very helpful.',
        account: 'english_user01',
        is_spam: false,
        is_judol: false,
        is_hidden: false,
        sentiment: 1,
    },
    {
        id: 24,
        comment: 'Coba bahas topik kayak gini lagi dong!',
        account: 'pengikut_setia',
        is_spam: false,
        is_judol: false,
        is_hidden: false,
        sentiment: 1,
    },
    {
        id: 25,
        comment: 'Masih banyak BO yang lebih bagus dari ini bro',
        account: 'komentar_aneh',
        is_spam: true,
        is_judol: true,
        is_hidden: false,
        sentiment: -1,
    },
    {
        id: 26,
        comment: 'Gak jelas kontennya, skip!',
        account: 'hater_mild',
        is_spam: false,
        is_judol: false,
        is_hidden: false,
        sentiment: -1,
    },
    {
        id: 27,
        comment: 'WETON88 paling mantap, no tipu-tipu',
        account: 'bot_akun02',
        is_spam: true,
        is_judol: true,
        is_hidden: false,
        sentiment: -1,
    },
    {
        id: 28,
        comment: 'Ditunggu part 2-nya ya min!',
        account: 'fans_berat',
        is_spam: false,
        is_judol: false,
        is_hidden: false,
        sentiment: 1,
    },
    {
        id: 29,
        comment: 'Cuan terus tiap hari! Gaskeun WETON88!',
        account: 'iklan_judi88',
        is_spam: true,
        is_judol: true,
        is_hidden: false,
        sentiment: -1,
    },
];
